### ISSUE TITLE
Code stopped working again

### ISSUE THREAD

**Issue by omegakode** [MicrosoftEdge/WebViewFeedback#156]
It's the same issue as
[https://github.com/MicrosoftEdge/WebViewFeedback/issues/151](https://github.com/MicrosoftEdge/WebViewFeedback/issues/151)

i have the current three channels installed but the code does not work.

**Comment by pontusn** [comment]
Possibly related: 
Using 84.0.485.0 we experience problems in some, but not all, sites where WebView2 is embedded. 

HRESULT = 0x8007139F

Code:
```
    HRESULT hRes = CreateCoreWebView2EnvironmentWithDetails(
        nullptr,
        szAppData,
        startArguments.data(),
        Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
            [this](HRESULT result, ICoreWebView2Environment* webviewEnvironment) -> HRESULT {
                ATLTRACE(_T("ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler\n"));
                m_spWebViewEnvironment = webviewEnvironment;
                if (!m_spWebViewEnvironment)
                {
                    m_strStatusMessage.Format(L"Failed to create environment. hResult=0x%08x", result);
                    return FAILED(result) ? result : E_FAIL;
                }
                m_spWebViewEnvironment->CreateCoreWebView2Host(m_hWnd, Callback<ICoreWebView2CreateCoreWebView2HostCompletedHandler>(
                    [this](HRESULT result, ICoreWebView2Host* webviewHost) -> HRESULT {
                        ATLTRACE(_T("ICoreWebView2CreateCoreWebView2HostCompletedHandler\n"));
                        m_spWebViewHost = webviewHost;
                        if (!m_spWebViewHost)
                        {
                            // Fails here with hResult = 0x8007139F
                            m_strStatusMessage.Format(L"Failed to create host. hResult=0x%08x", result);
                            return FAILED(result) ? result : E_FAIL;
                        }

                        if (FAILED(result = m_spWebViewHost->get_CoreWebView2(&m_spWebViewWindow)) || !m_spWebViewWindow)
                        {
                            m_strStatusMessage.Format(L"Failed to get view. hResult=0x%08x", result);
                            return FAILED(result) ? result : E_FAIL;
                        }

                        if (FAILED(result = InternalConfigure()))
                        {
                            m_strStatusMessage.Format(L"Failed to configure browser. hResult=0x%08x", result);
                            return result;
                        }

                        return S_OK;
                    }).Get());
                return S_OK;
            }).Get());
```

The problem was not seen with 84.0.484.0.

I will provide more details if I manage to pinpoint what is going on.

**Comment by omegakode** [comment]
My error code is 0x80004002

**Comment by pontusn** [comment]
We consistently get HRESULT_FROM_WIN32(ERROR_INVALID_STATE) for all but the first panel embedded in the main window.

I've tried to postpone creation using `PostMessage` and also tested retry via `SetTimer(id, 500)`.

**Comment by omegakode** [comment]
Just realized that the error only occurs in Windows 7, in Windows 10 the same code works, both OS are using the same canary version  84.0.485.0.

**Comment by pontusn** [comment]
I'm on Windows 10. 

omegakode <notifications@github.com> skrev: (15 april 2020 10:44:26 CEST)
>Just realized that the error only occurs in Windows 7, in Windows 10
>the same code works, both OS are using the same canary version 
>84.0.485.0.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/MicrosoftEdge/WebViewFeedback/issues/156#issuecomment-613904748

-- 
Skickat från min Android-enhet med K-9 Mail. Ursäkta min fåordighet.

**Comment by david-risney** [comment]
Very sorry about these issues! Thanks for letting us know. 

#151 is regarding failure from CreateCoreWebView2EnvironmentWithDetails with E_NOINTERFACE. @omegakode is this what you are seeing? And you say its only on Win7? The issue with #151 should be fixed in canary versions 482 and up so if you see it in 485 we'll need to look into this. Thanks for reporting!

@pontusn if the issue you see is from CreateCoreWebView2Host then this is a different issue from #151. If the problem is that the first WebView2 creation succeeds and subsequent creations fail

**Comment by omegakode** [comment]
@david-risney, yes it's the exact same issue, i get E_NOINTERFACE in the creation handler with a null ICoreWebView2Environment pointer. Only in Windows 7, windows 10 works.
The issue persists in the last 84.0.486.0 canary version.
It worked until the #151 issue.

**Comment by pontusn** [comment]
Also the 83.0.478.5 (dev) is broken with E_NOINTERFACE today for Windows 10.

**Comment by ASM-SW** [comment]
I got the E-NOINTERFACE issue with Dev 83.0.478.5 on Windows 10.  It worked last week but not today.  I switched to Canary, 84.0.486.0 and it worked.

**Comment by pontusn** [comment]
See #159 for additional information about the problem I commented about here.

**Comment by omegakode** [comment]
Now i have these versions installed and the code is working again in Windows 7.
can 84.0.488.0
dev 83.0.478.10
beta 81.0.416.58

**Comment by david-risney** [comment]
Apologies again for this issue but thanks for letting us know about it and glad to read that its working again. This bug should be fixed in browser 84.0.486.0 and up.
